### ISSUE TITLE
Mob Spawner Crash

### ISSUE THREAD

**Issue by Narotiza** [DragonEggBedrockBreaking/VanillaDisable#12]
```---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!
Time: 2023-03-12 00:05:06
Description: Ticking block entity
java.lang.NullPointerException: Ticking block entity
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at net.minecraft.class_1917.handler$djl000$cancelSpawningNewEntityAndPassengers(class_1917.java:530)
	at net.minecraft.class_1917.method_31588(class_1917.java:157)
	at net.minecraft.class_2636.method_31697(class_2636.java:54)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at net.minecraft.class_1917.handler$djl000$cancelSpawningNewEntityAndPassengers(class_1917.java:530)
	at net.minecraft.class_1917.method_31588(class_1917.java:157)
	at net.minecraft.class_2636.method_31697(class_2636.java:54)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
-- Block entity being ticked --
Details:
	Name: minecraft:mob_spawner // net.minecraft.class_2636
	Block: Block{minecraft:spawner}
	Block location: World: (9,69,1), Section: (at 9,5,1 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Block: Block{minecraft:spawner}
	Block location: World: (9,69,1), Section: (at 9,5,1 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
-- Affected level --
Details:
	All players: 1 total; [class_3222['Narotiza'/240, l='ServerLevel[Uhh vt?]', x=9.66, y=70.66, z=-2.09]]
	Chunk stats: 2401
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,0), Section: (at 0,6,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 609 game time, 609 day time
	Level name: Uhh vt?
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 137050 (now: false), thunder time: 131458 (now: false)
	Known server brands: quilt
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18-beta, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 683594392 bytes (651 MiB) / 2634022912 bytes (2512 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2560
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1236
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23670.39
	Virtual memory used (MB): 20964.08
	Swap memory total (MB): 7434.33
	Swap memory used (MB): 759.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		| Index | Mod                                               | ID                                                    | Version                      |
		|------:|---------------------------------------------------|-------------------------------------------------------|------------------------------|
		|    24 | Advancements Enlarger                             | advancements-enlarger                                 | 0.3.0                        |
		|   100 | Boring Default Game Rules                         | boring_default_game_rules                             | 1.0.1+1.19.2                 |
		|    26 | CIT Resewn                                        | citresewn                                             | 1.1.2+1.19.2                 |
		|    21 | CIT Resewn: Defaults                              | citresewn-defaults                                    | 1.1.2+1.19.2                 |
		|     8 | CaffeineConfig                                    | caffeineconfig                                        | 1.0.0                        |
		|    81 | Cloth Config v8                                   | cloth-config                                          | 8.2.88                       |
		|    73 | Collective                                        | collective                                            | 6.50                         |
		|    14 | Colormatic                                        | colormatic                                            | 3.1.2+mc.1.19                |
		|   132 | CombatEdit                                        | combatedit                                            | 1.6.1                        |
		|    87 | Craft 6 stairs not 4                              | sixstairs                                             | 1.19.2-10                    |
		|     0 | CrowdinTranslate                                  | crowdin-translate                                     | 1.4+1.19                     |
		|    25 | Dark Loading Screen                               | dark-loading-screen                                   | 1.6.12                       |
		|    48 | Fabrication                                       | fabrication                                           | 3.1.3+1.19                   |
		|   107 | Falling Leaves                                    | fallingleaves                                         | 1.13.0+1.19.2                |
		|    97 | Hunger Remover                                    | hunger_remover                                        | 1.0.4                        |
		|   136 | I Know What I'm Doing                             | iknowwhatimdoing                                      | 4.1.0                        |
		|    29 | JsonEM                                            | jsonem                                                | 0.1.2+1.19                   |
		|    19 | LazyDFU                                           | lazydfu                                               | 0.1.3                        |
		|   134 | Leaves Us In Peace                                | leaves_us_in_peace                                    | 1.0.12                       |
		|    47 | LessGlintyThings                                  | lessglintythings                                      | 1.2.0                        |
		|    16 | Lib39 (Deferral)                                  | lib39-deferral                                        | 1.1.1                        |
		|    98 | Lithium                                           | lithium                                               | 0.10.4                       |
		|   124 | Minecraft                                         | minecraft                                             | 1.19.2                       |
		|     2 | MixinExtras                                       | com_github_llamalad7_mixinextras                      | 0.1.0-rc5                    |
		|    15 | Mob Filter                                        | mobfilter                                             | 0.0.5+1.19.2                 |
		|    58 | Mod Menu                                          | modmenu                                               | 4.1.2                        |
		|    72 | NBT Crafting                                      | nbtcrafting                                           | 2.2.3+mc1.19                 |
		|    31 | Nostalgic Tweaks                                  | nostalgic_tweaks                                      | 1.2.2                        |
		|    37 | OpenJDK 64-Bit Server VM                          | java                                                  | 18                           |
		|   103 | Paxi                                              | paxi                                                  | 1.19.2-Fabric-3.0            |
		|   146 | Quilt Advancement API                             | quilt_advancement                                     | 3.0.0-beta.24+1.19.2         |
		|    65 | Quilt Base API                                    | quilt_base                                            | 3.0.0-beta.24+1.19.2         |
		|    85 | Quilt Biome API                                   | quilt_biome                                           | 3.0.0-beta.24+1.19.2         |
		|   143 | Quilt Block Content Registry API                  | quilt_block_content_registry                          | 3.0.0-beta.24+1.19.2         |
		|    59 | Quilt Block Entity API                            | quilt_block_entity                                    | 3.0.0-beta.24+1.19.2         |
		|    43 | Quilt Block Extensions API                        | quilt_block_extensions                                | 3.0.0-beta.24+1.19.2         |
		|    84 | Quilt Client Command API                          | quilt_client_command                                  | 3.0.0-beta.24+1.19.2         |
		|    41 | Quilt Command API                                 | quilt_command                                         | 3.0.0-beta.24+1.19.2         |
		|    82 | Quilt Crash Info                                  | quilt_crash_info                                      | 3.0.0-beta.24+1.19.2         |
		|    71 | Quilt DataFixerUpper API                          | quilt_datafixerupper                                  | 3.0.0-beta.24+1.19.2         |
		|    54 | Quilt Dimension API                               | quilt_dimension                                       | 3.0.0-beta.24+1.19.2         |
		|    66 | Quilt Entity API                                  | quilt_entity                                          | 3.0.0-beta.24+1.19.2         |
		|   126 | Quilt Entity Events                               | quilt_entity_events                                   | 3.0.0-beta.24+1.19.2         |
		|    55 | Quilt Entity Networking API                       | quilt_entity_networking                               | 3.0.0-beta.24+1.19.2         |
		|    34 | Quilt Item Content Registry API                   | quilt_item_content_registry                           | 3.0.0-beta.24+1.19.2         |
		|    69 | Quilt Item Extension API                          | quilt_item_extension                                  | 3.0.0-beta.24+1.19.2         |
		|    94 | Quilt Item Group API                              | quilt_item_group                                      | 3.0.0-beta.24+1.19.2         |
		|    32 | Quilt Item Setting API                            | quilt_item_setting                                    | 3.0.0-beta.24+1.19.2         |
		|   101 | Quilt Kotlin Libraries                            | qkl                                                   | 1.0.0                        |
		|    86 | Quilt Kotlin Libraries: Core                      | qkl_core                                              | 1.0.0                        |
		|   145 | Quilt Kotlin Libraries: Library                   | qkl_library                                           | 1.0.0                        |
		|   129 | Quilt Lifecycle Events                            | quilt_lifecycle_events                                | 3.0.0-beta.24+1.19.2         |
		|    88 | Quilt Loader                                      | quilt_loader                                          | 0.17.7                       |
		|    39 | Quilt Multipart Entity API                        | quilt_entity_multipart                                | 3.0.0-beta.24+1.19.2         |
		|   110 | Quilt Networking                                  | quilt_networking                                      | 3.0.0-beta.24+1.19.2         |
		|    67 | Quilt Points of Interest                          | quilt_points_of_interest                              | 3.0.0-beta.24+1.19.2         |
		|   116 | Quilt Recipe API                                  | quilt_recipe                                          | 3.0.0-beta.24+1.19.2         |
		|    96 | Quilt Registry API                                | quilt_registry                                        | 3.0.0-beta.24+1.19.2         |
		|    80 | Quilt Registry Entry Attachment                   | quilt_registry_entry_attachment                       | 3.0.0-beta.24+1.19.2         |
		|   104 | Quilt Resource Loader                             | quilt_resource_loader                                 | 3.0.0-beta.24+1.19.2         |
		|   102 | Quilt Screen API                                  | quilt_screen                                          | 3.0.0-beta.24+1.19.2         |
		|   131 | Quilt Status Effect API                           | quilt_status_effect                                   | 3.0.0-beta.24+1.19.2         |
		|   121 | Quilt Surface Rule API                            | quilt_surface_rule                                    | 3.0.0-beta.24+1.19.2         |
		|   106 | Quilt Tags API                                    | quilt_tags                                            | 3.0.0-beta.24+1.19.2         |
		|   122 | Quilt Tooltip API                                 | quilt_tooltip                                         | 3.0.0-beta.24+1.19.2         |
		|    56 | Quilt Vehicle API                                 | quilt_vehicle                                         | 3.0.0-beta.24+1.19.2         |
		|    61 | Quilt Villager API                                | quilt_villager                                        | 3.0.0-beta.24+1.19.2         |
		|   111 | Quilted Fabric API                                | quilted_fabric_api                                    | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    79 | Quilted Fabric API Base                           | quilted_fabric_api_base                               | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    90 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1                      | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    74 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                           | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   133 | Quilted Fabric Block API (v1)                     | quilted_fabric_block_api_v1                           | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   144 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1                    | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   142 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1                     | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    51 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                         | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    53 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                         | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    49 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                            | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    64 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                          | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   137 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0                  | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    62 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1                 | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    40 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1                   | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    83 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1                 | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   112 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                          | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    63 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1                       | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   120 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0                  | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    77 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0                    | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    42 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1                       | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    68 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                            | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    35 | Quilted Fabric Item Groups (v0)                   | quilted_fabric_item_groups_v0                         | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   147 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1                     | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   127 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                         | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    89 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1                    | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   119 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                            | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    33 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                         | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    76 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                         | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   139 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1                    | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    75 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                              | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    44 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                          | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    38 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1                      | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    60 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1                  | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   138 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                           | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   123 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0                       | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    91 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo                        | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    36 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1                        | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    46 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1                 | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   105 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                           | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   108 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                           | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    57 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1           | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    95 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1                    | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    50 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1             | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   130 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0                     | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   135 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                          | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   113 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1                  | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   115 | Quilted Fabric Sound API (v1)                     | quilted_fabric_sound_api_v1                           | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   117 | Quilted Fabric Textures (v0)                      | quilted_fabric_textures_v0                            | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   109 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1                        | 4.0.0-beta.24+0.68.0-1.19.2  |
		|    92 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1          | 4.0.0-beta.24+0.68.0-1.19.2  |
		|   141 | Raised                                            | raised                                                | 1.2.1                        |
		|   114 | Reach Entity Attributes                           | reach-entity-attributes                               | 2.3.0                        |
		|    10 | Reese's Sodium Options                            | reeses-sodium-options                                 | 1.4.9+mc1.19.2-build.67      |
		|    52 | Skip Transitions                                  | skiptransitions                                       | 1.3.2+1.18.x                 |
		|   118 | Sodium                                            | sodium                                                | 0.4.4+build.18               |
		|    78 | Sodium Shadowy Path Blocks                        | sspb                                                  | 3.1.0                        |
		|    99 | SomeOrdinaryTweaks                                | ordinarytweaks                                        | 1.6.0                        |
		|     3 | Take it Slow                                      | takeitslow                                            | 1.0.3                        |
		|    70 | Use Glowstone dust as Glow Ink Sac                | glowstoneinc                                          | 1.19.2-2                     |
		|   128 | Vanilla Disable                                   | vanilla_disable                                       | 2.2.0                        |
		|   125 | Weaker Spiderwebs                                 | weakerspiderwebs                                      | 3.2                          |
		|   140 | Why is there Auto Jump?                           | yisthereautojump                                      | 1.2.0                        |
		|    45 | YUNG's API                                        | yungsapi                                              | 1.19.2-Fabric-3.8.2          |
		|    11 | atomicfu-jvm                                      | org_jetbrains_kotlinx_atomicfu-jvm                    | 0.18.4                       |
		|    22 | cloth-basic-math                                  | cloth-basic-math                                      | 0.6.1                        |
		|    27 | conditional mixin                                 | conditional-mixin                                     | 0.3.1                        |
		|    20 | javassist                                         | org_javassist_javassist                               | 3.28.0-GA                    |
		|     5 | joml                                              | org_joml_joml                                         | 1.10.4                       |
		|    13 | kotlin-reflect                                    | org_jetbrains_kotlin_kotlin-reflect                   | 1.7.20                       |
		|     6 | kotlin-stdlib                                     | org_jetbrains_kotlin_kotlin-stdlib                    | 1.7.20                       |
		|     7 | kotlin-stdlib-jdk7                                | org_jetbrains_kotlin_kotlin-stdlib-jdk7               | 1.7.20                       |
		|     9 | kotlin-stdlib-jdk8                                | org_jetbrains_kotlin_kotlin-stdlib-jdk8               | 1.7.20                       |
		|    23 | kotlinx-coroutines-core-jvm                       | org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm     | 1.6.4                        |
		|    12 | kotlinx-coroutines-jdk8                           | org_jetbrains_kotlinx_kotlinx-coroutines-jdk8         | 1.6.4                        |
		|    17 | kotlinx-datetime-jvm                              | org_jetbrains_kotlinx_kotlinx-datetime-jvm            | 0.4.0                        |
		|    28 | kotlinx-serialization-cbor-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm  | 1.4.1                        |
		|    18 | kotlinx-serialization-core-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-core-jvm  | 1.4.1                        |
		|     1 | kotlinx-serialization-json-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-json-jvm  | 1.4.1                        |
		|     4 | reflections                                       | org_reflections_reflections                           | 0.10.2                       |
		|    93 | sihywtcamc                                        | sihywtcamc                                            | 1.4.2+1.19                   |
		|    30 | snakeyaml                                         | org_yaml_snakeyaml                                    | 1.29                         |
		|------:|---------------------------------------------------|-------------------------------------------------------|------------------------------|
		
	Server Running: true
	Player Count: 1 / 8; [class_3222['Narotiza'/240, l='ServerLevel[Uhh vt?]', x=9.66, y=70.66, z=-2.09]]
	Data Packs: vanilla, leaves_us_in_peace/oak_leaves_recognize_jungle_logs, .modified-hybrid-beta-1-19-v0-9-4, Hunger Debuff Replacer (incompatible), Less Lapis, MC Minus Structures, MM Achievements (incompatible), MM Loot+Recipes (incompatible), MM World, Ruined Classic Villages (incompatible), Snowcapped.zip
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'quilt'; Server brand changed to 'quilt'
	Launched Version: 1.19.2```

**Comment by DragonEggBedrockBreaking** [comment]
Please can you describe when this issue occurred?

**Comment by Narotiza** [comment]
Seems to be any time I'm close enough to a mob spawner for it to spawn mobs. I first got the crash in a survival world because of a zombie dungeon underground, and also got it when i placed down a pig spawner in creative. (which i think was the source of this log)
EDIT: I was able to recreate the crash in a new instance with only Quilted Fabric API and Mod Menu installed, so it can't be a conflict with another mod. The crash doesn't seem to happen in 1.19.3

**Comment by DragonEggBedrockBreaking** [comment]
Please test the latest commit. You can do this by going into the "Actions" tab at the top, clicking on the top commit, scrolling down, downloading the zip file, unzipping the zip file, then running the .jar file. If there is more than one .jar file, use the one with the shortest filename.

**Comment by Narotiza** [comment]
It's not compatible with 1.19.2

**Comment by DragonEggBedrockBreaking** [comment]
I have updated the 1.19.2 branch with the crash fix. Please check GitHub actions again.

**Comment by Narotiza** [comment]
Looks like it works, thank you!

**Comment by DragonEggBedrockBreaking** [comment]
Fixed in latest release.
https://github.com/DragonEggBedrockBreaking/VanillaDisable/releases/tag/v2.2.1
