### ISSUE TITLE
Non-vanilla advancements cause `ArrayIndexOutOfBoundsException` when splitting display string

### ISSUE THREAD

**Issue by worstending** [DragonEggBedrockBreaking/VanillaDisable#13]
Version: 2.4.0 for 1.20
Fabric 0.14.21 on both client and server.

While I was under the assumption this was a server side mod, after getting this error I joined with it installed on the client, and regardless it seems I'm still getting this error on my server's console: 
[22:49:41] [User Authenticator #4/INFO]: UUID of player worstending is 113f4188-8816-42e9-870b-d2e67510b8de
[22:49:41] [Server thread/ERROR]: Couldn't place player in world
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at net.minecraft.class_2985.modifyReturnValue$zkm000$vanilla_disable$cancelPerformingCriterion(class_2985.java:1017) ~[server-intermediary.jar:?]
        at net.minecraft.class_2985.method_12882(class_2985.java:297) ~[server-intermediary.jar:?]
        at net.minecraft.class_2985.method_12874(class_2985.java:218) ~[server-intermediary.jar:?]
        at net.minecraft.class_2985.method_12889(class_2985.java:98) ~[server-intermediary.jar:?]
        at net.minecraft.class_2985.method_12873(class_2985.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.class_2985.<init>(class_2985.java:72) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14578(class_3324.java:877) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.<init>(class_3222.java:272) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14613(class_3324.java:479) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:113) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$zdl000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:254) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:49:41] [Server thread/INFO]: com.mojang.authlib.GameProfile@d9d730[id=113f4188-8816-42e9-870b-d2e67510b8de,name=worstending,properties={textures=[com.mojang.authlib.properties.Property@a445241]},legacy=false] **(/IP)** lost connection: Invalid player data
[22:49:41] [Netty Epoll Play IO Thread #3/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.StacklessClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(ChannelPromise)(Unknown Source) ~[netty-transport-4.1.82.Final.jar:?]
[22:49:41] [Server thread/WARN]: handleDisconnection() called twice

![image](https://github.com/DragonEggBedrockBreaking/VanillaDisable/assets/88409163/0f5a5668-98a8-4406-96ff-5d1bfdc37bfe)

**Comment by DragonEggBedrockBreaking** [comment]
I noticed this issue once but it's very hard to reproduce. This seems to be caused by the advancement toggles, so in the file on the server in `.config/vanilla-disable-mixin.properties` add the line `mixin.advancement=false`. This is a temporary fix (it disabled all advancement toggling code) until I find the cause of the bug and fix it properly.

**Comment by DragonEggBedrockBreaking** [comment]
Btw, for debug purposes, could you tell me what advancements the players had (or at least those that you had)?

**Comment by worstending** [comment]
I only had one, and it was from a datapack I put together for my server that gave it's root upon joining. Thanks though!

**Comment by DragonEggBedrockBreaking** [comment]
Fixed in 2.4.1 (see modrinth/github releases).
